apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: infra-secrets
  namespace: argocd
spec:
  refreshInterval: 1h # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets # name of the SecretStore (or kind specified)
  target:
    name: infra-secrets # name of the k8s Secret to be created
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: k8s1-infra # name of the GCPSM secret
