apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: private-gitops-deploy-secrets
  namespace: argocd
spec:
  refreshInterval: 1h # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets # name of the SecretStore (or kind specified)
  target:
    name: private-gitops-deploy-secrets # name of the k8s Secret to be created
    template:
      type: kubernetes.io/ssh-auth
      data:
        ssh-privatekey: "{{ .mysecret | toString }}"
    creationPolicy: Owner
  data:
    - secretKey: mysecret
      remoteRef:
        key: k8s1-github-private-gitops-deploy
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-private-gitops-ssh
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    name: argocd-private-gitops-ssh
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      type: Opaque
      data:
        type: git
        url: https://github.com/monnierant/private-gitops
        sshPrivateKey: "{{ .mysecret | toString }}"
  data:
    - secretKey: mysecret
      remoteRef:
        key: k8s1-github-private-gitops-deploy
