apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: twingate-secrets
  namespace: argocd
spec:
  refreshInterval: 1h # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets # name of the SecretStore (or kind specified)
  target:
    template:
      type: Opaque
      engineVersion: v2
      data:
        service_key.json: "{{ .k8s1-twingate | toString }}"
    name: twingate-secrets # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: k8s1-twingate
      remoteRef:
        key: k8s1-twingate
