apiVersion: v1
kind: ConfigMap
metadata:
  name: mcp-configs
  namespace: n8n
data:
  mcp-config: ""
  mcp-tools: ""
  mcp-registry: |
    registry:
      mcp-discord:
        ref: ""
      notion:
        ref: ""
      playwright:
        ref: ""
