apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mcpgateway-secret
  namespace: n8n
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets # ton store GCP (ou autre)
  target:
    name: mcpgateway-secret # Secret consommé par le StatefulSet
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: k8s1-mcpgateway # Nom du secret dans Google Secret Manager

