apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-encryption-secret
  namespace: n8n
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets # ton store GCP (ou autre)
  target:
    name: n8n-encryption # Secret consommé par le StatefulSet
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        encryption-key: "{{ .encryptionKey | toString }}"
  data:
    - secretKey: encryptionKey
      remoteRef:
        key: k8s1-n8n-encryption-key # Nom du secret dans Google Secret Manager
