apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: n8n
  namespace: n8n
spec:
  serviceName: n8n
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
        - name: n8n
          image: docker.n8n.io/n8nio/n8n
          securityContext:
            runAsUser: 1000
            runAsGroup: 0
            fsGroup: 1000
            fsGroupChangePolicy: Always
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "0"
            - name: UMASK
              value: "002"
            - name: TZ
              value: "Europe/Paris"
            - name: N8N_SECURE_COOKIE
              value: "true"
            - name: N8N_EDITOR_BASE_URL
              value: "https://n8n.promonni.com/"
            - name: WEBHOOK_URL
              value: "https://n8n.promonni.com/"
            - name: N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE
              value: "true"
            - name: N8N_PORT
              value: "5678"
            - name: N8N_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: n8n-encryption
                  key: encryption-key
          volumeMounts:
            - name: n8n-data
              mountPath: /home/node/.n8n
      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: n8n-data
