apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: external-secrets
spec:
  provider:
    gcpsm:
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcp-sa-secret
            key: secret-access-credentials
            namespace: external-secrets
      projectID: amonnier
