apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-repos
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: https://github.com/monnierant/gitops
    path: external-repos
    targetRevision: HEAD
    plugin:
      name: argocd-vault-plugin
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
