apiVersion: v1
kind: Namespace
metadata:
  name: traefik
  labels:
    name: traefik
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 36.1.0
    helm:
      releaseName: traefik
      valuesFiles:
        - traefik-values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik
