apiVersion: v1
kind: Namespace
metadata:
  name: traefik-external
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/audit: privileged
    pod-security.kubernetes.io/warn: privileged
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 36.1.0
    helm:
      releaseName: traefik
      values: |
        globalArguments:
          - "--global.sendAnonymousUsage=false"
          - "--global.checkNewVersion=false"
        additionalArguments:
          - "--serverstransport.insecureSkipVerify=true"
          - "--providers.kubernetescrd.allowCrossNamespace=true"
          - "--log.level=INFO"
          - "--certificatesresolvers.letsencrypt-prod.acme.email=<path:infra-secrets#email>"
          - "--certificatesresolvers.letsencrypt-prod.acme.storage=/data/acme.json"
          - "--certificatesresolvers.letsencrypt-prod.acme.tlschallenge=true"
          - "--entrypoints.web.address=:80"
          - "--entrypoints.websecure.address=:443"
          - "--api.dashboard=true"
          - "--providers.kubernetescrd"
          - "--providers.kubernetesingress"
        nodeSelector:
          kubernetes.io/hostname: <path:infra-secrets#traefik-node-name>
        deployment:
          enabled: true
          replicas: 1
          annotations: {}
          podAnnotations: {}
          additionalContainers: []
          initContainers: []
        ports:
          web:
            port: 80
            expose:
              default: true
            exposedPort: 80
            protocol: TCP
            hostPort: 80
            # redirections:
            #   entryPoint:
            #     to: websecure        # nom de l’entryPoint cible
            #     scheme: https        # (optionnel) force le schéma https
            #     permanent: true      # (optionnel) 308 Permanent Redirect
          websecure:
            port: 443
            expose:
              default: true
            exposedPort: 443
            protocol: TCP
            hostPort: 443
            tls:
              enabled: true
        ingressRoute:
          dashboard:
            enabled: false
        providers:
          kubernetesCRD:
            enabled: true
            ingressClass: traefik
          kubernetesIngress:
            enabled: true
            publishedService:
              enabled: true
        rbac:
          enabled: true
        service:
          enabled: false
          # annotations: {}
          # type: LoadBalancer
          # loadBalancerIP: <path:infra-secrets#traefik-loadbalancer-ip
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik-external
