apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 36.1.0
    helm:
      releaseName: traefik
      values: |
        globalArguments:
          - "--global.sendAnonymousUsage=false"
          - "--global.checkNewVersion=false"
        additionalArguments:
          - "--serverstransport.insecureSkipVerify=true"
          - "--providers.kubernetescrd.allowCrossNamespace=true"
          - "--log.level=INFO"
        deployment:
          enabled: true
          replicas: 1
          annotations: {}
          podAnnotations: {}
          additionalContainers: []
          initContainers: []
        ports:
          web:
            redirections:
              entryPoint:
                to: websecure        # nom de l’entryPoint cible
                scheme: https        # (optionnel) force le schéma https
                permanent: true      # (optionnel) 308 Permanent Redirect
          websecure:
            tls:
              enabled: true
        ingressRoute:
          dashboard:
            enabled: false
        providers:
          kubernetesCRD:
            enabled: true
            ingressClass: traefik-external
          kubernetesIngress:
            enabled: true
            publishedService:
              enabled: true
        rbac:
          enabled: true
        service:
          enabled: true
          annotations: {}
          type: NodePort
          externalTrafficPolicy: Local
          ports:
            web:
              port: 80
              targetPort: web
            websecure:
              port: 443
              targetPort: websecure
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik-external
