apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: traefik
spec:
  project: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    chart: traefik/traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 36.1.0
    helm:
      releaseName: traefik
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik
