apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik-helm
  namespace: argocd
spec:
  project: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    chart: authentik
    repoURL: https://charts.goauthentik.io
    targetRevision: 2025.10.1
    helm:
      releaseName: authentik
      values: |
        postgresql:
          enabled: true
          auth:
            existingSecret: authentik-creds
        redis:
          enabled: true
        server:
          env:
            - name: AUTHENTIK_POSTGRESQL__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik-creds
                  key: password
            - name: AUTHENTIK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: authentik-creds
                  key: secret_key
          ingress:
            ingressClassName: traefik
            enabled: true
            annotations:
              - traefik.ingress.kubernetes.io/router.entrypoints: websecure
              - traefik.ingress.kubernetes.io/router.tls: "true"
              - traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt-prod
            hosts:
              - authentik.amonnier.fr
            tls:
              - hosts:
                  - authentik.amonnier.fr
                secretName: authentik-tls
        worker:
          env:
            - name: AUTHENTIK_POSTGRESQL__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik-creds
                  key: password
            - name: AUTHENTIK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: authentik-creds
                  key: secret_key
  destination:
    server: "https://kubernetes.default.svc"
    namespace: authentik
