apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-creds
  namespace: authentik
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets # ton store GCP (ou autre)
  target:
    name: authentik-creds
    creationPolicy: Owner
  data:
    - secretKey: KEYSETS_JSON
      remoteRef:
        key: k8s1-authentik # name of the secret in your external secret store
