apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: obsidian-data
  namespace: obsidian
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi # adapte la taille selon tes besoins
  storageClassName: longhorn
