# Proprietes attendues dans le secret externe k8s1-keycloak :
#   db-password    : mot de passe de l'utilisateur Postgres "keycloak"
#   admin-password : mot de passe du compte admin bootstrap (a changer apres le 1er login)
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-creds
  namespace: keycloak
spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    name: keycloak-creds
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: k8s1-keycloak
