apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: api-gw-keysets
  namespace: security
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: gcp-secretstore # your existing (Cluster)SecretStore
    kind: ClusterSecretStore
  target:
    name: api-gw-keysets
    creationPolicy: Owner
  data:
    - secretKey: KEYSETS_JSON
      remoteRef:
        key: k8s1-api-gw-keysets # name of the secret in your external secret store

