apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: external-secrets
  target:
    name: grafana-admin
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: k8s1-grafana # secret GCPSM : { "admin-user": "...", "admin-password": "..." }
