apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: private-gitops
  namespace: argocd
spec:
  project: infra
  source:
    repoURL: git@github.com:monnierant/private-gitops.git
    path: "main"
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
