apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-exemple
  namespace: argocd
spec:
  project: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    chart: echo-server
    repoURL: https://ealenn.github.io/charts
    targetRevision: 0.5.0
    helm:
      releaseName: echo-server
      values: |
        replicaCount: 3
        ingress:
          enabled: true
          hosts:
            - host: echo.amonnier.fr
              paths:
                - / 
          annotations:
            kubernetes.io/ingress.class: traefik
            traefik.ingress.kubernetes.io/router.entrypoints: websecure
            traefik.ingress.kubernetes.io/router.tls: "true"
            traefik.ingress.kubernetes.io/router.tls.certresolver: letsencrypt-prod

  destination:
    server: "https://kubernetes.default.svc"
    namespace: helm-exemple-external
